 version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: sqlpreview
    hostname: sqlpreview
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong()Password"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - nopnet

  nopcommerce:
    image: nopcommerceteam/nopcommerce:latest
    container_name: nopcommerce
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=nopcommerce;User Id=sa;Password=yourStrong()Password;
    volumes:
      - nop_data:/app
    networks:
      - nopnet

volumes:
  sql_data:
  nop_data:

networks:
  nopnet:
